#!/bin/sh

uci -q batch <<-EOF >/dev/null
    set network.lan=interface
    set network.lan.type='bridge'
    set network.lan.proto='static'
    set network.lan.ipaddr='192.168.1.1'
    set network.lan.netmask='255.255.255.0'
    set network.lan.device='br-lan'
    set network.lan.dns='8.8.8.8'
    commit network
EOF

uci -q batch <<-EOF >/dev/null
    set network.tsmodem=interface
    set network.tsmodem.username='root'
    set network.tsmodem.proto='3g'
    set network.tsmodem.device='/dev/ttyUSB2'
    set network.tsmodem.dialnumber='*99***1#'
    set network.tsmodem.service='umts'
    set network.tsmodem.pppd_options='noipdefault'
    set network.tsmodem.keepalive='500 5'
    set network.tsmodem.ipv6='auto'
    set network.tsmodem.ip4table='default'
    set network.tsmodem.ip6table='default'
    set network.tsmodem.apn='internet.megafon.ru'
    commit network 
EOF

uci -q batch <<-EOF >/dev/null
    set network.wifi=interface
    set network.wifi.proto='static'
    set network.wifi.device='phy0-ap0'
    set network.wifi.ipaddr='192.168.2.1'
    set network.wifi.netmask='255.255.255.0'
    set network.wifi.ip4table='default'
    set network.wifi.ip6table='default'
    commit network
EOF

uci -q batch <<-EOF >/dev/null
    add dhcp tsmodem
    set dhcp.tsmodem.interface='tsmodem'
    set dhcp.tsmodem.start='100'
    set dhcp.tsmodem.limit='150'
    set dhcp.tsmodem.leasetime='12h'
    commit dhcp
EOF

uci -q batch <<-EOF >/dev/null
    set firewall.@defaults[0]=defaults
    set firewall.@defaults[0].input='ACCEPT'
    set firewall.@defaults[0].output='ACCEPT'
    set firewall.@defaults[0].forward='ACCEPT'
    set firewall.@defaults[0].synflood_protect='1'
    set firewall.@zone[0]=zone
    set firewall.@zone[0].name='lan'
    set firewall.@zone[0].input='ACCEPT'
    set firewall.@zone[0].output='ACCEPT'
    set firewall.@zone[0].forward='ACCEPT'
    set firewall.@zone[0].masq='1'
    set firewall.@zone[0].network='lan' 'tsmodem'
    commit firewall
EOF

uci -q batch <<-EOF >/dev/null
    set wireless.radio0=wifi-device
    set wireless.radio0.type='mac80211'
    set wireless.radio0.hwmode='11g'
    set wireless.radio0.path='platform/10300000.wmac'
    set wireless.radio0.htmode='HT20'
    set wireless.radio0.disabled='1'
    set wireless.radio0.channel='1'
    set wireless.radio0.band='2g'
    set wireless.radio0.cell_density='1'
    set wireless.default_radio0=wifi-iface
    set wireless.default_radio0.device='radio0'
    set wireless.default_radio0.mode='ap'
    set wireless.default_radio0.network='wwan wifi'
    set wireless.default_radio0.ssid='BITCORD-RTR-2'
    set wireless.default_radio0.encryption='psk2'
    set wireless.default_radio0.key='WFCLokm7Ls'
    commit wireless
EOF

uci -q batch <<-EOF >/dev/null
    set luci.main.lang='ru'
    set luci.main.mediaurlbase='/luci-static/tsmodem'
    set luci.languages=internal
    set luci.languages.ru='Русский (Russian)'
    set luci.ccache=internal
    set luci.ccache.enable='0'
    set luci.themes=internal
    set luci.themes.Bootstrap='/luci-static/bootstrap'
    set luci.themes.tsmodem='/luci-static/tsmodem'
    commit luci
EOF

exit 0


